server:
  port: 8089
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 494563742290-l969e1ik0inbrhahh51dkn030gcrh1u3.apps.googleusercontent.com
            clientSecret: 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

  mail:
    host: smtp.gmail.com
    port: 587
    username: itechlib2021@gmail.com
    password: ejxcrthehwivjvac
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

template:
  host: ${TEMPLATE_HOST}

jwt:
  secret: 8b4f7dd2-9884-4b96-af62-66e25441390e

cron:
  check-confirm-data: "00 00 01 * * *"
  check-bookings: "30 00 00 * * *"
  check-bookings-remind-finish-date: "00 00 00 * * *"

isDevelopment: false

application-data:
  users:
    -
      name: Maksim
      surname: Mayeusky
      corpEmail: maksim.mayeuski@itechart-group.com
      isActive: true
    -
      name: Aliaksandr
      surname: Silchanka
      corpEmail: aliaksandr.silchanka@itechart-group.com
      isActive: true
    -
      name: Siarhei
      surname: Semiantsou
      corpEmail: siarhei.semiantsou@itechart-group.com
      isActive: true
    -
      name: Yanina
      surname: Hutyro
      corpEmail: yanina.hutyro@itechart-group.com
      isActive: true
    -
      name: Pavel
      surname: Baranau
      corpEmail: Pavel.Baranau@itechart-group.com
      isActive: true
    -
      name: Liubou
      surname: Zhyhalka
      corpEmail: liubou.zhyhalka@itechart-group.com
      isActive: true
    -
      name: Aleh
      surname: Bautunou
      corpEmail: Aleh.Bautunou@itechart-group.com
      isActive: true
    -
      name: Ilyas
      surname: Sadziyeu
      corpEmail: ilyas.sadziyeu@itechart-group.com
      isActive: true
    -
      name: Maksim
      surname: Chyryk
      corpEmail: maksim.chyryk@itechart-group.com
      isActive: true
    -
      name: Natallia
      surname: Halounich
      corpEmail: natallia.halounich@itechart-group.com
      isActive: true
    -
      name: TestName
      surname: TestSurname
      corpEmail: test.itechlib@itechart-group.com
      isActive: true
    -
      name: Sergey
      surname: Kuzmianok
      corpEmail: sergey.kuzmianok@itechart-group.com
      isActive: true
    -
      name: Katsiaryna
      surname: Yashchanka
      corpEmail: k.yashchanka@itechart-group.com
      isActive: true
