server:
  port: 8089
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 494563742290-l969e1ik0inbrhahh51dkn030gcrh1u3.apps.googleusercontent.com
            clientSecret: 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

  mail:
    host: smtp.gmail.com
    port: 587
    username: itechlib2021@gmail.com
    password: Nestor911
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
