name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/Development
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
  - task: DockerCompose@0
    displayName: Build
    inputs:
      azureSubscriptionEndpoint: d9b77d09-828b-4adf-952c-1f5e31c4729a
      azureContainerRegistry: '{"loginServer":"itechlib.azurecr.io", "id" : "/subscriptions/f8fb46e7-4cee-4c80-9477-c2cab11daf88/resourceGroups/itechlib/providers/Microsoft.ContainerRegistry/registries/itechlib"}'
      dockerComposeFile: docker-compose.yml
      projectName: itechlib2021
      action: Build services
  - task: DockerCompose@0
    displayName: Push
    inputs:
      azureSubscriptionEndpoint: d9b77d09-828b-4adf-952c-1f5e31c4729a
      azureContainerRegistry: '{"loginServer":"itechlib.azurecr.io", "id" : "/subscriptions/f8fb46e7-4cee-4c80-9477-c2cab11daf88/resourceGroups/itechlib/providers/Microsoft.ContainerRegistry/registries/itechlib"}'
      dockerComposeFile: docker-compose.yml
      projectName: itechlib2021
      action: Push services
      includeLatestTag: true
  - task: CopyFilesOverSSH@0
    displayName: Securely copy files to the remote machine
    inputs:
      sshEndpoint: fe5c2b10-e5a1-42da-9138-1258219fefdc
      sourceFolder: Azure
      targetFolder: /home/azureuser/
  - task: SSH@0
    displayName: Run shell inline on remote machine
    inputs:
      sshEndpoint: fe5c2b10-e5a1-42da-9138-1258219fefdc
      runOptions: inline
      commands: >2+


      inline: >-
        #!/bin/bash

        docker-compose down 2> docker-compose.log

        sleep 20

        docker image prune -af

        sleep 20

        docker-compose --env-file ~/.env up -d --build 2> docker-compose.log
...
