export const books = [
  {
    id: 1,
    title: 'Book 1',
    author: 'Ivan Ivanov',
    category: 'Technical',
    language: 'English',
    link: 'https://www.amazon.com/C-Programming-Language-4th/dp/0321563840',
    rating: 0,
    status: 'Available',
    description: 'Some description about the book',
  },
  {
    id: 2,
    title: 'Book 2',
    author: 'Sergey Petrov',
    category: 'Technical',
    language: 'English',
    link: 'https://www.amazon.com/C-Programming-Language-4th/dp/0321563840',
    rating: 0,
    status: 'Not available',
    description: 'Some description about the book',
  },
  {
    id: 3,
    title: 'Book 3',
    author: 'Petr Petrov',
    category: 'Technical',
    language: 'English',
    link: 'https://www.amazon.com/C-Programming-Language-4th/dp/0321563840',
    rating: 0,
    status: 'Available',
    description: 'Some description about the book',
  },
]
