version: '3.7'

volumes:
  itech-lib-data:

networks:
  lib-network:

services:

  library_service_application:
    container_name: ${LIBRARY_SERVICE_CONTAINER}
    image: itechlib/library_service:serv
    restart: always
    build:
      context: ./server/java/itechlibrary/
    ports:
      - "${LIBRARY_SERVICE_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://itech_library_database:5432/${POSTGRES_DB_NAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      TEMPLATE_HOST: ${TEMPLATE_HOST}
    depends_on:
      - itech_library_database
    networks:
      - lib-network


  itech_library_database:
    container_name: ${DATABASE_SERVICE_CONTAINER}
    restart: always
    image: postgres:${POSTGRES_DB_VERSION}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - itech-lib-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    networks:
      - lib-network


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - lib-network
 
  node:
    build: 
      context: . 
      dockerfile: Dockerfile
    image: itechlib/library_service:front  
    restart: always 
    ports: 
      - "3000:3000"
    container_name: node_lib
    networks:
      - lib-network
      
  nginx:
    container_name: nginx
    restart: always
    image: itechlib/library_service:nginx
    build:
      context: ./NGINX/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
     - lib-network
  
