import { v4 as uuid } from "uuid";

export const books = [
  {
    id: uuid(),
    title: "title of the book",
    author: "Ivan Ivanov",
    cathegory: "Technical",
    language: "English",
    description: "Some description about the book",
    rating: 5,
    status: "available",
  },
  {
    id: uuid(),
    title: "title",
    author: "Ivan Ivanov",
    cathegory: "Technical",
    language: "English",
    description: "Some description about the book",
    rating: 5,
    status: "available",
  },
  {
    id: uuid(),
    title: "title of the book",
    author: "Ivan Ivanov",
    cathegory: "Technical",
    language: "English",
    description: "Some description about the book",
    rating: 5,
    status: "available",
  },
  {
    id: uuid(),
    title: "title of the book",
    author: "Ivan Ivanov",
    cathegory: "Technical",
    language: "English",
    description: "Some description about the book",
    rating: 5,
    status: "available",
  },
  {
    id: uuid(),
    title: "title of the book",
    author: "Ivan Ivanov",
    cathegory: "Technical",
    language: "English",
    description: "Some description about the book",
    rating: 5,
    status: "available",
  },
  {
    id: uuid(),
    title: "title",
    author: "Ivan Ivanov",
    cathegory: "Technical",
    language: "English",
    description: "Some description about the book",
    rating: 5,
    status: "available",
  },
  {
    id: uuid(),
    title: "title of the book",
    author: "Ivan Ivanov",
    cathegory: "Technical",
    language: "English",
    description: "Some description about the book",
    rating: 5,
    status: "available",
  },
  {
    id: uuid(),
    title: "title of the book",
    author: "Ivan Ivanov",
    cathegory: "Technical",
    language: "English",
    description: "Some description about the book",
    rating: 5,
    status: "available",
  },
  {
    id: uuid(),
    title: "title of the book",
    author: "Ivan Ivanov",
    cathegory: "Technical",
    language: "English",
    description: "Some description about the book",
    rating: 5,
    status: "available",
  },
  {
    id: uuid(),
    title: "title of the book",
    author: "Ivan Ivanov",
    cathegory: "Technical",
    language: "English",
    description: "Some description about the book",
    rating: 5,
    status: "available",
  },
];
