version: '3.9'

volumes:
  itech-lib-data:

networks:
  lib-network:

services:

  storage_service_application:
    container_name: library-service
    restart: always
    build:
      context: .
    ports:
      - ${STORAGE_SERVICE_PORT}:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://itech_library_database:5432/itech_lib
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_USERNAME: postgres
    depends_on:
      - itech_library_database
    networks:
      - lib-network


  itech_library_database:
    container_name: postgres
    restart: always
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - itech-lib-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: itech_lib
    networks:
      - lib-network


