version: '3.9'

volumes:
  itech-lib-data:

networks:
  lib-network:

services:

  library_service_application:
    container_name: ${LIBRARY_SERVICE_CONTAINER}
    restart: always
    build:
      context: .
    ports:
      - ${LIBRARY_SERVICE_PORT}:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://itech_library_database:5432/${POSTGRES_DB_NAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
    depends_on:
      - itech_library_database
    networks:
      - lib-network


  itech_library_database:
    container_name: ${DATABASE_SERVICE_CONTAINER}
    restart: always
    image: postgres:${POSTGRES_DB_VERSION}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - itech-lib-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    networks:
      - lib-network


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - target: 80
        published: 5050
        protocol: tcp
        mode: host
    networks:
      - lib-network


