INSERT INTO book_status (name)
VALUES ('AVAILABLE') ON CONFLICT (id) DO NOTHING;
INSERT INTO book_status (name)
VALUES ('NOT AVAILABLE') ON CONFLICT (id) DO NOTHING;
INSERT INTO book_status (name)
VALUES ('IN USE') ON CONFLICT (id) DO NOTHING;

INSERT INTO category (name)
VALUES ('PROFESSIONAL') ON CONFLICT (id) DO NOTHING;
INSERT INTO category (name)
VALUES ('FICTION') ON CONFLICT (id) DO NOTHING;

INSERT INTO language (name)
VALUES ('ENGLISH') ON CONFLICT (id) DO NOTHING;
INSERT INTO language (name)
VALUES ('RUSSIAN') ON CONFLICT (id) DO NOTHING;
